//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.HospitalManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nurse
    {
        public Nurse()
        {
            this.Patient_Medical_Test = new HashSet<Patient_Medical_Test>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> WardId { get; set; }
    
        public virtual Ward Ward { get; set; }
        public virtual ICollection<Patient_Medical_Test> Patient_Medical_Test { get; set; }
    }
}
