//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.HospitalManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorRecomendation
    {
        public int Id { get; set; }
        public Nullable<int> RecomendedDoctorId { get; set; }
        public Nullable<int> CurrentDoctorId { get; set; }
        public string Reason { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Doctor Doctor1 { get; set; }
    }
}
