//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.HospitalManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSpeciality
    {
        public DoctorSpeciality()
        {
            this.Doctors = new HashSet<Doctor>();
        }
    
        public int DoctorSpecialityId { get; set; }
        public string SpecializeArea { get; set; }
    
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}
