//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.HospitalManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Patient_Detail = new HashSet<Patient_Detail>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NIC { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string MobileNo { get; set; }
    
        public virtual ICollection<Patient_Detail> Patient_Detail { get; set; }
    }
}
