//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.HospitalManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Medical_Test
    {
        public int Id { get; set; }
        public int Patient_Detail_Id { get; set; }
        public Nullable<int> Medical_TestId { get; set; }
        public int NurseId { get; set; }
    
        public virtual Medical_Test_Type Medical_Test_Type { get; set; }
        public virtual Nurse Nurse { get; set; }
        public virtual Patient_Detail Patient_Detail { get; set; }
    }
}
