//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.HospitalManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Test_Type
    {
        public Medical_Test_Type()
        {
            this.Patient_Medical_Test = new HashSet<Patient_Medical_Test>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Patient_Medical_Test> Patient_Medical_Test { get; set; }
    }
}
